### ISSUE TITLE
Reduze the size of the docker image

### ISSUE THREAD

**Issue by lmmendes** [tarbase/docker-pritunl#1]
Test building the `docker-pritunl` using `alpine` linux as the base image instead of the `ubuntu` to see if the size can be squeezed.

**Comment by lmmendes** [comment]
Using the commited Dockerfile (62e6204) the alpine image is bigger than the one based on `ubuntu:16.04`

| REPOSITORY  | IMAGE ID      |     SIZE |
|---------------|-------------|---------|
| alpine-docker-pritunl |    build     |   621 MB |
tarbase/docker-pritunl   | latest      |329 MB |

Using `docker-squash` (v1.0.5) the `alpine-docker-pritunl` image with 621 MB can be squeezed to 174 MB

**Comment by include** [comment]
refactored.
