### ISSUE TITLE
pritunl/container can't be gracefully stopped!

### ISSUE THREAD

**Issue by lmmendes** [tarbase/docker-pritunl#2]
The container cannot be gracefully stopped 😓! We should implemente something like [dumb-init](https://github.com/Yelp/dumb-init) or [runit](http://smarden.org/runit/index.html) to correctly handle processes, signals and reaping of process if necessary. 

Literature about the subject
- https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
- https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86#.7qjvec91g

**Comment by include** [comment]
refactored.
